apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthy-app-demo
  namespace: default
  labels:
    app: healthy-app-demo
    managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthy-app-demo
  template:
    metadata:
      labels:
        app: healthy-app-demo
    spec:
      containers:
      - name: app
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 128Mi
        # Health checks configured to be ready in ~10 seconds
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        # Startup probe to handle initial container startup
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 2
          timeoutSeconds: 3
          failureThreshold: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: healthy-app-demo
  namespace: default
  labels:
    app: healthy-app-demo
spec:
  selector:
    app: healthy-app-demo
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
