apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: test-namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: "18.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: test-namespace
      interval: 1h
  values:
    auth:
      enabled: false
    replica:
      replicaCount: 4
    master:
      persistence:
        enabled: false
    metrics:
      enabled: false
    commonConfiguration: |-
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly yes
      # Disable RDB persistence, AOF persistence already enabled.
      save ""
