apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system

resources:
  - ../../flux-system
  - apps.yaml

patchesStrategicMerge:
  - gotk-sync.yaml

patches:
  - target:
      kind: GitRepository
      name: flux-system
    patch: |-
      - op: replace
        path: /spec/url
        value: https://github.com/dangwn/k8s-sandbox
      - op: replace
        path: /spec/ref/branch
        value: main