apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: ${SYNC_INTERVAL}
  ref:
    branch: ${REPOSITORY_BRANCH}
  url: ${REPOSITORY_URL}