apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: ${KUSTOMIZATION_INTERVAL}
  path: ${FLUX_PATH}
  prune: ${PRUNE_ENABLED}
  sourceRef:
    kind: GitRepository
    name: flux-system