---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 1h0m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: base
      version: "1.22.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: false
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      version: "1.22.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  values:
    global:
      istioNamespace: istio-system
    meshConfig:
      mode: AMBIENT
    pilot:
      autoscaleEnabled: true
    components:
      ztunnel:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  releaseName: ztunnel
  chart:
    spec:
      chart: ztunnel
      version: "1.22.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: istiod
      namespace: istio-system
  values:
    global:
      istioNamespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  releaseName: istio-ingressgateway
  chart:
    spec:
      chart: gateway
      version: "1.22.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: istiod
      namespace: istio-system
    - name: ztunnel
      namespace: istio-system
  values:
    service:
      type: LoadBalancer
    global:
      istioNamespace: istio-system
    ztunnel:
      enabled: true
