---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: base
      version: "1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: false
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      version: "1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  values:
    global:
      istioNamespace: istio-system
    meshConfig:
      defaultConfig:
        proxyStatsMatcher:
          inclusionRegexps:
          - ".*circuit_breakers.*"
          - ".*upstream_rq_retry.*"
          - ".*upstream_rq_pending.*"
          - ".*_cx_.*"
          - ".*osconfig.*"
          - ".*wasm.*"
      mode: AMBIENT
    pilot:
      autoscaleEnabled: true
      env:
        PILOT_ENABLE_AMBIENT: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  releaseName: istio-cni
  chart:
    spec:
      chart: cni
      version: "1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: istiod
      namespace: istio-system
  values:
    global:
      istioNamespace: istio-system
    cni:
      ambient:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  releaseName: ztunnel
  chart:
    spec:
      chart: ztunnel
      version: "1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: istio-cni
      namespace: istio-system
  values:
    global:
      istioNamespace: istio-system