apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: points-are-bad
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: "20.0.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  values:
    auth:
      enabled: true
      existingSecret: ""
      existingSecretPasswordKey: ""
    architecture: standalone
    master:
      count: 1
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ""
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    replica:
      replicaCount: 0
    sentinel:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
    commonConfiguration: |-
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly yes
      # Disable RDB persistence, AOF persistence already enabled.
      save ""