apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: healthy-app-demo
  namespace: flux-system
spec:
  interval: 30s
  path: ./apps/healthy-app-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system